name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_ROOT_USER }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Python packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt -r requirements/dev-requirements.txt

      - name: Run tests
        run: |
          sudo systemctl start mysql
          sudo systemctl status mysql
          mysql -u ${{ secrets.DB_ROOT_USER }} -p"${{ secrets.DB_ROOT_PASSWORD }}" <<MYSQL_SCRIPT || handle_error "Failed to execute MySQL tasks."
          CREATE DATABASE IF NOT EXISTS webApp;
          CREATE USER IF NOT EXISTS '${{ secrets.DB_USER }}'@'localhost' IDENTIFIED BY '${{ secrets.DB_USER_PASSWORD }}';
          GRANT ALL PRIVILEGES ON *.* TO '${{ secrets.DB_USER }'@'localhost';
          FLUSH PRIVILEGES;
          MYSQL_SCRIPT
          python manage.py makemigrations
          python manage.py migrate
          python manage.py test
