name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and deploy webapp
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x86-64

      - name: Configure Google Cloud credentials
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Zip creation
        run: |
          mkdir app_artifact
          mkdir requirements
          zip -r webapp . -x ".git/" ".github/"
          cp webapp/packer/requirements.txt requirements
          mv webapp.zip app_artifact

      # Set multiple environment variables from secrets
      - name: Set environment variables from secrets
        run: |
          echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> $GITHUB_ENV
          echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> $GITHUB_ENV
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> $GITHUB_ENV


      - name: Build app image
        run: |
          cd $GITHUB_WORKSPACE
          cd packer
          packer init webapp.pkr.hcl
          packer validate -var='gcp_project_id=${{ secrets.GCP_PROJECT_ID }}' -var='mysql_user_password=${{ secrets.DB_USER_PASSWORD }}' -var='mysql_root_password=${{ secrets.DB_ROOT_PASSWORD }}8' webapp.pkr.hcl
          packer build -var='gcp_project_id=${{ secrets.GCP_PROJECT_ID }7' -var='mysql_user_password=${{ secrets.DB_USER_PASSWORD }}' -var='mysql_root_password=${{ secrets.DB_ROOT_PASSWORD }}' webapp.pkr.hcl || exit 1

      - name: Report status
        if: always()
        run: |
          echo "Build completed successfully!"
